version: "2"

services:
  python-3-13:
    container_name: python-3-13-test
    image: python:3.13.3-bookworm@sha256:ee8747fc77699389c19486f15346466285731b4cb1378c514be1da9dbd399fba
    working_dir: /app
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./requirements.txt:/app/requirements.txt
      - ./lowkeyvault.pem:/app/lowkeyvault.pem
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - |
        mkdir -p /var/opt/azcmagent/tokens/
        touch /var/opt/azcmagent/tokens/assumed-identity.key
        python -m venv ./venv
        python -m pip install --upgrade pip 
        python -m pip install pytest
        pip install -r requirements.txt 
        python -m pytest tests/test.py
    environment:
      REQUESTS_CA_BUNDLE: lowkeyvault.pem
      AZURE_POD_IDENTITY_AUTHORITY_HOST: http://lowkey-vault:8080
      IDENTITY_ENDPOINT: http://lowkey-vault:8080/metadata/identity/oauth2/token
      IMDS_ENDPOINT: http://lowkey-vault:8080
      LOWKEY_VAULT_URL: https://lowkey-vault:8443

    # use the previously defined network to let us access the lowkey-vault container
    networks:
      - lowkey-vault-python-net

networks:
  lowkey-vault-python-net:
    name: lowkey-vault-python-net
    external: true
